In [80]:
import numpy as np 
import pandas as pd

### Creating a DataFrame

In [81]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)  #Way to create DataFrame by dictionary; Keys of Dictionary are set as column heading

In [82]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [83]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)  #If we use other DS as list or array we have to manually set columns otherwise by default it got set to 0 ,1 ,2, and so on

In [84]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and Indexing of Columns

In [85]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [86]:
#For selecting the column we have to give its label in index braces
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [87]:
#For selecting multiple columns we have to give their label in form of list in index b_jupyterlab_variableinspector_getshapeof
df2[["Name","Age","Salary"]]

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

### Creating a new column

In [88]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [89]:
df2["Designation"] = ["Data Scientist","Data Analyst","Risk Analyst","Engineer"]  #The number of values provided in new Column should equal to rest of columns otherwise it gives error

In [90]:
df2

    Name  Age      City  Salary     Designation
0   John   28  New York   65000  Data Scientist
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000    Risk Analyst
3  Linda   42    London   85000        Engineer

### Removing Columns

In [91]:
df2

    Name  Age      City  Salary     Designation
0   John   28  New York   65000  Data Scientist
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000    Risk Analyst
3  Linda   42    London   85000        Engineer

By default axis of dataframes set to 0 for selecting columns we have to set axis to 1 because axis 0 only reads row sections

In [92]:
df2.drop("City",axis=1)

    Name  Age  Salary     Designation
0   John   28   65000  Data Scientist
1   Anna   34   70000    Data Analyst
2  Peter   29   62000    Risk Analyst
3  Linda   42   85000        Engineer

But after we execute dataframe again the dropped column appear again

In [93]:
df2

    Name  Age      City  Salary     Designation
0   John   28  New York   65000  Data Scientist
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000    Risk Analyst
3  Linda   42    London   85000        Engineer

For avoiding this we have to do:

In [94]:
df2.drop("City",axis=1,inplace=True)

In [95]:
df2

    Name  Age  Salary     Designation
0   John   28   65000  Data Scientist
1   Anna   34   70000    Data Analyst
2  Peter   29   62000    Risk Analyst
3  Linda   42   85000        Engineer

In [96]:
#For dropping multiple columns we have to give them in list form
df2.drop(["Salary","Name"],axis=1)

   Age     Designation
0   28  Data Scientist
1   34    Data Analyst
2   29    Risk Analyst
3   42        Engineer

### Selecting Rows

For removing rows we have to do simply change axis to 0 and write labels of rows

In [97]:
df2.drop(0,axis=0)

    Name  Age  Salary   Designation
1   Anna   34   70000  Data Analyst
2  Peter   29   62000  Risk Analyst
3  Linda   42   85000      Engineer

In [98]:
df2

    Name  Age  Salary     Designation
0   John   28   65000  Data Scientist
1   Anna   34   70000    Data Analyst
2  Peter   29   62000    Risk Analyst
3  Linda   42   85000        Engineer

In [102]:
# For selecting row we have to use .loc attribute
df2.loc[0]

Name                     John
Age                        28
Salary                  65000
Designation    Data Scientist
Name: 0, dtype: object

In [103]:
# And for multiple rows we have to give rows' labels in listabs
df2.loc[[0,2]]

    Name  Age  Salary     Designation
0   John   28   65000  Data Scientist
2  Peter   29   62000    Risk Analyst

If we had other row labels like any word or something then we can use .iloc attribute to know data of row at location of index

In [104]:
df2.iloc[3]  # 3 is location of 3rd index

Name              Linda
Age                  42
Salary            85000
Designation    Engineer
Name: 3, dtype: object

### Selecting Subsets of Rows and Columns

Same as of matrix slicing in NumPy

In [106]:
df2.loc[[0,1]][["Name","Salary"]]

   Name  Salary
0  John   65000
1  Anna   70000

### Conditional Selection

In [109]:
df2

    Name  Age  Salary     Designation
0   John   28   65000  Data Scientist
1   Anna   34   70000    Data Analyst
2  Peter   29   62000    Risk Analyst
3  Linda   42   85000        Engineer

People whose Age is greater than 30

In [117]:
df2[df2["Age"]>30]  #Same as Conditionals of NumPy array

    Name  Age  Salary   Designation
1   Anna   34   70000  Data Analyst
3  Linda   42   85000      Engineer

People whose age is grater than 30 and they should have salary greater than 75000

In [125]:
df2[(df2["Age"]>30) & (df2["Salary"]>75000)]

    Name  Age  Salary Designation
3  Linda   42   85000    Engineer