In [1]:
import numpy as np 
import pandas as pd

**GroupBy**

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [10]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [11]:
cat = df.groupby("Category")['Sales']  #It makes group of different Categories
for i,j in cat:
    print(i)
    print(j)

A
0    100
2    150
4    120
6    200
Name: Sales, dtype: int64
B
1    200
3    250
5    180
7    300
Name: Sales, dtype: int64

In [12]:
df.groupby("Category")['Sales'].sum()  #It makes group of different Categories and prints sum of its sales

Category
A    570
B    930
Name: Sales, dtype: int64

In [13]:
df.groupby("Store")['Sales'].sum()  #It makes of group of different Stores and prints sum of its sales

Store
S1    720
S2    780
Name: Sales, dtype: int64

Group by multiple columns

In [18]:
df.groupby(["Store","Category"])["Sales"].sum()

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

**Aggregation**

In [19]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [20]:
df['Sales'].mean()

np.float64(187.5)

In [25]:
df['Quantity'].median()

15.0

In [26]:
df['Sales'].std()

66.06274074155351

In [27]:
df['Sales'].max()

300

In [28]:
df['Sales'].min()

100

In [30]:
df['Quantity'].mode()

0    15
Name: Quantity, dtype: int64

In [34]:
df['Sales'].agg(['sum',"mean",'median','max','min','std'])  #Aggregation allows to do multiple statistic operation in one go

sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
min        100.000000
std         66.062741
Name: Sales, dtype: float64